# -*- coding: utf-8 -*-
"""Exp1_subjectwise_pairwise_accuracy.ipynb

Automatically generated by Colaboratory.

"""

from sklearn.linear_model import Ridge
import numpy as np
from scipy.io import loadmat
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from scipy.stats import pearsonr
from sklearn.model_selection import KFold
import json

# fmri_pict = loadmat('../input/data/M10/inf_voxels/M10_glove_concepts_pictures.mat')
# fmri_wc = loadmat('../input/data/M10/inf_voxels/M10_glove_concepts_wordclouds.mat')
# fmri_sent = loadmat('../input/data/M10/inf_voxels/M10_glove_concepts_sentences.mat')
fmri_pict = loadmat('../input/data/M10_glove_concepts_pictures.mat')
fmri_wc = loadmat('../input/data/M10_glove_concepts_wordclouds.mat')
fmri_sent = loadmat('../input/data/M10_glove_concepts_sentences.mat')

voxels_p_p = fmri_pict['voxels_pictures_final']
voxels_w_w = fmri_wc['voxels_wordclouds_final']
voxels_s_s = fmri_sent['voxels_sentences_final']

concepts = []
f = open('../data/stimuli_180concepts.txt','r')
lines = f.readlines()

for line in lines:
    concepts.append(line.strip())

glove_vectors = []

f = open('../input/data/vectors_180concepts.GV42B300.txt','r')
lines = f.readlines()

for line in lines:
    line = line.strip().split(' ')
    line = list(map(float, line))
    glove_vectors.append(line)

out_file = open("../input/data/bert_roberta_sentvec.json", "r") 
concept2vec = json.load(out_file)

bert_vectors = []
keys = list(concept2vec['bert'].keys())

for key in keys:
    bert_vectors.append(concept2vec['bert'][key])

roberta_vectors = []
keys = list(concept2vec['roberta'].keys())

for key in keys:
    roberta_vectors.append(concept2vec['roberta'][key])

def accuracy(actual, predicted):
    true = 0
    total = 0
    for i in range(0,len(actual)):
        for j in range(i+1, len(actual)):
            total += 1

            s1 = actual[i]
            s2 = actual[j]
            b1 = predicted[i]
            b2 = predicted[j]

            if(pearsonr(s1,b1)[0] + pearsonr(s2,b2)[0] > pearsonr(s1,b2)[0] + pearsonr(s2,b1)[0]):
                true += 1

    return(true/total)

kf = KFold(n_splits=18)

# def train(vectors, train_voxels, test1_voxels, test2_voxels):
def train(vectors, train_voxels):

    
    dataset_X = np.array(train_voxels.copy())
    
    dataset_Y = np.array(vectors.copy())

    accuracies = []
    
    actual = []
    predicted = []

    cnt = 0
    for train_index, test_index in kf.split(dataset_X[cnt]):

        X_train, X_test = dataset_X[cnt][train_index], dataset_X[cnt][test_index]
        y_train, y_test = dataset_Y[train_index], dataset_Y[test_index]
        
        
        model = Ridge(alpha=1.0)
        model.fit(X_train,y_train)

        
        y_pred = model.predict(X_test)
        acc = accuracy(y_test,y_pred)
        accuracies.append(acc)
        
        actual.extend(y_test)
        predicted.extend(y_pred)

        
        cnt +=1 
        print("fold: ",cnt)
        print("accuracy: ", acc)
        print()

    accuracies = np.array(accuracies)
    fin_acc = accuracy(actual,predicted)

    return np.mean(accuracies),fin_acc

"""### Using glove vectors"""

# acc,fin_acc = train(glove_vectors,voxels_p_p,voxels_p_w,voxels_p_s)
acc,fin_acc = train(glove_vectors,voxels_p_p)

print("Pictures training accuaracy:",round(acc,2))
print("Pictures final training accuaracy:",round(fin_acc,2))
print()

# acc,acc1,acc2,fin_acc = train(glove_vectors,voxels_s_s,voxels_s_w,voxels_s_p)
acc,acc1,acc2,fin_acc = train(glove_vectors,voxels_s_s)

print("Sentences training accuaracy:",round(acc,2))
print("Sentences final training accuaracy:",round(fin_acc,2))
print()

# acc,acc1,acc2,fin_acc = train(glove_vectors,voxels_w_w,voxels_w_p,voxels_w_s)
acc,acc1,acc2,fin_acc = train(glove_vectors,voxels_w_w)

print("Wordclouds training accuaracy:",round(acc,2))
print("Wordclouds final training accuaracy:",round(fin_acc,2))
print()

"""### Using bert vectors"""

fmri_pict = loadmat('../input/data/M10/inf_voxels/M10_bert_concepts_pictures.mat')
fmri_wc = loadmat('../input/data/M10/inf_voxels/M10_bert_concepts_wordclouds.mat')
# fmri_sent = loadmat('../input/data/M10/inf_voxels/M10_bert_concepts_sentences.mat')

voxels_p_p = fmri_pict['voxels_pictures_final']
voxels_p_s = fmri_pict['voxels_sentences_final']
voxels_p_w = fmri_pict['voxels_wordclouds_final']

voxels_w_p = fmri_wc['voxels_pictures_final']
voxels_w_s = fmri_wc['voxels_sentences_final']
voxels_w_w = fmri_wc['voxels_wordclouds_final']

# voxels_s_p = fmri_sent['voxels_pictures_final']
# voxels_s_s = fmri_sent['voxels_sentences_final']
# voxels_s_w = fmri_sent['voxels_wordclouds_final']

acc,acc1,acc2,fin_acc = train(bert_vectors,voxels_p_p,voxels_p_w,voxels_p_s)
print("Pictures training accuaracy:",round(acc,2))
print("Pictures final training accuaracy:",round(fin_acc,2))
print("Sentences testing accuracy:",round(acc2,2))
print("Wordclouds testing accuracy:",round(acc1,2))
print()

# acc,acc1,acc2,fin_acc = train(bert_vectors,voxels_s_s,voxels_s_w,voxels_s_p)
# print("Sentences training accuaracy:",round(acc,2))
# print("Sentences final training accuaracy:",round(fin_acc,2))
# print("Pictures testing accuracy:",round(acc2,2))
# print("Wordclouds testing accuracy:",round(acc1,2))
# print()

acc,acc1,acc2,fin_acc = train(bert_vectors,voxels_w_w,voxels_w_p,voxels_w_s)
print("Wordclouds training accuaracy:",round(acc,2))
print("Wordclouds final training accuaracy:",round(fin_acc,2))
print("Sentences testing accuracy:",round(acc2,2))
print("Pictures testing accuracy:",round(acc1,2))
print()

"""### Using roberta vectors"""

fmri_pict = loadmat('../input/data/M10/inf_voxels/M10_roberta_concepts_pictures.mat')
fmri_wc = loadmat('../input/data/M10/inf_voxels/M10_roberta_concepts_wordclouds.mat')
fmri_sent = loadmat('../input/data/M10/inf_voxels/M10_roberta_concepts_sentences.mat')

voxels_p_p = fmri_pict['voxels_pictures_final']
voxels_p_s = fmri_pict['voxels_sentences_final']
voxels_p_w = fmri_pict['voxels_wordclouds_final']

voxels_w_p = fmri_wc['voxels_pictures_final']
voxels_w_s = fmri_wc['voxels_sentences_final']
voxels_w_w = fmri_wc['voxels_wordclouds_final']

voxels_s_p = fmri_sent['voxels_pictures_final']
voxels_s_s = fmri_sent['voxels_sentences_final']
voxels_s_w = fmri_sent['voxels_wordclouds_final']

acc,acc1,acc2,fin_acc = train(roberta_vectors,voxels_p_p,voxels_p_w,voxels_p_s)
print("Pictures training accuaracy:",round(acc,2))
print("Pictures final training accuaracy:",round(fin_acc,2))
print("Sentences testing accuracy:",round(acc2,2))
print("Wordclouds testing accuracy:",round(acc1,2))
print()

acc,acc1,acc2,fin_acc = train(roberta_vectors,voxels_s_s,voxels_s_w,voxels_s_p)
print("Sentences training accuaracy:",round(acc,2))
print("Sentences final training accuaracy:",round(fin_acc,2))
print("Pictures testing accuracy:",round(acc2,2))
print("Wordclouds testing accuracy:",round(acc1,2))
print()

acc,acc1,acc2,fin_acc = train(roberta_vectors,voxels_w_w,voxels_w_p,voxels_w_s)
print("Wordclouds training accuaracy:",round(acc,2))
print("Wordclouds final training accuaracy:",round(fin_acc,2))
print("Sentences testing accuracy:",round(acc2,2))
print("Pictures testing accuracy:",round(acc1,2))
print()

